### ISSUE TITLE
history-graph is not shown on expanded card

### ISSUE THREAD

**Issue by RomanDidenko** [RossMcMillan92/lovelace-collapsable-cards#12]
history-graph is not shown on expanded card:

```yaml
 - type: custom:vertical-stack-in-card
    cards:
      - type: 'custom:collapsable-cards'
        title: Details
        cards:
          - type: history-graph
            title: 'co2'
            entities:
              - entity: sensor.cleargrass_air_co2a
```

![image](https://user-images.githubusercontent.com/4664877/123612150-f82e7980-d80a-11eb-9d69-e4128d0c3a3f.png)

collapsable-cards: v0.0.1
HA: core-2021.6.6
Chrome: v91.0
