### ISSUE TITLE
Unable to View Header on Light Theme

### ISSUE THREAD

**Issue by woodmj74** [RossMcMillan92/lovelace-collapsable-cards#5]
Have a card configured as:
```
type: 'custom:collapsable-cards'
title: TEST
cards:
  - type: entities
    entities:
      - entity: light.office_play
```

My HA instance is set to use the light built in theme:
![image](https://user-images.githubusercontent.com/68328701/119315264-93ad5700-bc6d-11eb-999f-a543caccfe21.png)

When I view the above card on the dashboard the header is white on white, unless I click on it then it is white on grey:
![image](https://user-images.githubusercontent.com/68328701/119315408-b475ac80-bc6d-11eb-9eec-ae79eb2ba0f3.png)
![image](https://user-images.githubusercontent.com/68328701/119315452-bfc8d800-bc6d-11eb-908a-a6f9bb86e2e2.png)

If I flip to the built in dark theme it appears fine:
![image](https://user-images.githubusercontent.com/68328701/119315618-f0107680-bc6d-11eb-9379-4820b255d608.png)

Was wondering if there is anything I can do to resolve this (or something I'm doing wrong!)? Otherwise, great card and thanks for your hard work, looks great
